
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Manual equivalent of pressing the global Escape hotkey — the pill's
 * cancel button (`#pill-cancel`) invokes this, since a webview button click
 * can't itself register as a global-shortcut key-press.
 */
async cancelRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetrics() : Promise<Result<MetricsDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLanguageBreakdown() : Promise<Result<LanguageStatDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_language_breakdown") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the Stats page's activity chart (2026-08-30 redesign) — see
 * `HistoryStore::daily_activity`'s doc comment for why this is a real
 * backend aggregate rather than the frontend bucketing raw history pages.
 */
async getDailyActivity(days: number) : Promise<Result<DailyActivityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_daily_activity", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLatencyStats() : Promise<Result<LatencyStatsDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latency_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryPage(page: number, pageSize: number) : Promise<Result<HistoryEntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_page", { page, pageSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the history list's "copy" button — Section 8: "doubles as the
 * copy-and-paste-at-any-time recovery mechanism".
 */
async copyHistoryText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_history_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the dashboard Settings panel's Permissions row — real OS-queried
 * status (permissions.rs), not the "not yet wired" placeholder it started
 * as.
 */
async getPermissionStatus() : Promise<PermissionStatusDto> {
    return await TAURI_INVOKE("get_permission_status");
},
/**
 * Deep-links to the matching System Settings pane for Accessibility and
 * Screen Recording (macOS has no active-request API for either — unlike
 * mic, see `request_mic_access` below). Also the fallback path for mic
 * once its one-shot native prompt (`request_mic_access`) has already been
 * answered, since that prompt won't show again.
 * 
 * `async` + `spawn_blocking`, matching `request_mic_access` right below —
 * a plain sync `#[tauri::command]` runs on the same thread that dispatches
 * the IPC message (the main/UI thread for the default wry/WKWebView
 * backend), so `Command::status()`'s blocking wait for `open` to launch
 * would otherwise stall the UI for however long that takes (review finding,
 * caught by inconsistency with the sibling command below it).
 */
async openPermissionSettings(kind: PermissionKind) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_permission_settings", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the real native macOS mic-permission prompt (Outside Voice finding
 * #2 from the onboarding-flow plan review — mic gets an active request,
 * unlike Accessibility/Screen Recording, which stay on
 * `open_permission_settings` above). Blocking, so it's dispatched onto
 * Tauri's blocking-task pool rather than the async command's own task —
 * never call the underlying native function from the main thread.
 */
async requestMicAccess() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_mic_access") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Marks onboarding as finished — persisted so it never shows again — then
 * closes the onboarding window and shows the dashboard. Awaited by the
 * frontend with its "Open Dashboard" button disabled while pending, so a
 * `settings.json` save failure (disk full, permissions) surfaces as a
 * real error instead of silently leaving `onboarding_completed=false`
 * (which would otherwise only be discoverable as "onboarding weirdly
 * reappears next launch").
 */
async completeOnboarding() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the dashboard sidebar's quit button. The tray menu's predefined
 * "Quit" item (see `run()`) is the primary quit path; this is the same
 * action reachable from the dashboard itself, per the reference mockup's
 * sidebar layout — not worth adding the separate `tauri-plugin-process`
 * dependency for one button when `AppHandle::exit` already does this.
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async getRecoveryInfo() : Promise<string | null> {
    return await TAURI_INVOKE("get_recovery_info");
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
/**
 * Backs the dashboard's hotkey-configuration rows (Section 4: "hotkey
 * configuration (separate bindings for mic-dictation mode and system-audio
 * mode)"). `mode` is `"mic"` or `"system_audio"` — a plain string over the
 * wire rather than reusing `hotkey::HotkeyMode` directly, since that enum
 * isn't (and doesn't need to be) `Deserialize`.
 */
async setHotkey(mode: string, shortcut: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hotkey", { mode, shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs the dashboard's grammar-cleanup toggle (Section 5, "Option B").
 * Updates the live flag `GrammarPipeline` reads immediately (no restart
 * needed — the very next transcript picks it up) and persists to
 * `settings.json` via the same `Mutex<AppSettings>` `set_hotkey` uses.
 */
async setGrammarLlmCleanupEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_grammar_llm_cleanup_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backs every new Settings toggle except grammar-LLM-cleanup (which keeps
 * its own dedicated `set_grammar_llm_cleanup_enabled` command — pre-existing,
 * left untouched). Same live-flag-plus-persisted-settings dual-update shape
 * as that command, just generalized over `SettingField` (D3) instead of
 * hardcoded to one field.
 */
async setBoolSetting(field: SettingField, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_bool_setting", { field, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `Pill.tsx` calls this on load and whenever `#pill`'s own rendered width
 * changes (it varies per state — listening shows a waveform/timer/
 * controls, done/canceling show just an icon+status — even though the
 * window itself is non-resizable-by-the-user, so a `ResizeObserver` on
 * `#pill` itself is what drives this, not a window resize event).
 * 
 * Delegates to `session::apply_pill_layout`, which resizes+repositions the
 * real window to fit, only while it's visible or about to become visible —
 * see that function's docs for the real bug this guards against (acting on
 * a *hidden* window left a persistent WindowServer compositing ghost, and
 * this command fires on every page load regardless of window visibility,
 * so every launch used to trigger it). No vibrancy masking happens here
 * any more — the pill's native glass shell is applied once, at startup,
 * via `vibrancy::apply_glass_shell` — see `vibrancy.rs`'s module doc.
 */
async setPillContentWidth(width: number) : Promise<void> {
    await TAURI_INVOKE("set_pill_content_width", { width });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { mic_hotkey: string; system_audio_hotkey: string; 
/**
 * Section 5, Option B — off by default: it's an opt-in ~390MB download
 * plus real per-transcript latency, not something to silently turn on
 * for existing or new users. See `engine::pipeline::GrammarPipeline`
 * for how this is actually consumed (checked live, not just at
 * startup) and `engine::llm_cleanup` for the always-on-vs-per-
 * transcript tradeoff this toggle represents.
 */
grammar_llm_cleanup_enabled?: boolean; 
/**
 * Off = copy the transcript to the clipboard only, never call
 * `injection::insert_at_cursor`. See `injection.rs`'s module docs for
 * why "restore the clipboard" and "auto-paste" are related but
 * separately toggleable concerns.
 */
paste_automatically?: boolean; 
/**
 * Only meaningfully affects the clipboard-*fallback* injection path
 * (terminals, apps without a settable AX text value) — the primary
 * Accessibility-API path never touches the clipboard at all, so this
 * toggle has no effect there. See `injection.rs`.
 */
restore_clipboard?: boolean; 
/**
 * `engine::grammar`'s `capitalise_first_letter` step — despite the
 * UI label ("Capitalise sentences"), this capitalises only the first
 * character of the whole transcript, matching `RuleBasedCleanup`'s
 * pre-rewrite behavior exactly (real per-sentence capitalisation was
 * considered and explicitly scoped out — see the frontend-rewrite
 * plan's `/plan-eng-review` notes).
 */
capitalise_sentences?: boolean; 
/**
 * `engine::grammar`'s `tidy_punctuation` step (whitespace collapse +
 * terminal punctuation) — `RuleBasedCleanup`'s other pre-rewrite
 * always-on behavior, now toggleable.
 */
tidy_punctuation?: boolean; 
/**
 * `engine::grammar`'s `remove_filler_words` step — strips "um", "uh",
 * "you know" and similar. New in the frontend-rewrite plan.
 */
remove_filler_words?: boolean; 
/**
 * `engine::grammar`'s `apply_spoken_formatting` step — turns spoken
 * phrases like "new line"/"comma"/"period" into the literal characters
 * they name. New in the frontend-rewrite plan.
 */
spoken_formatting?: boolean; 
/**
 * `engine::grammar`'s `apply_spoken_corrections` step — detects
 * spoken self-corrections ("I meant X", "make that X") and keeps only
 * the correction. New in the frontend-rewrite plan; rule-based
 * heuristic, documented ceiling in `engine/grammar.rs`.
 */
apply_spoken_corrections?: boolean; 
/**
 * Gates the onboarding window (`lib.rs`'s `setup()`) — `false` for
 * both brand-new installs and any existing `settings.json` predating
 * this field (`#[serde(default)]`'s zero value), so an upgrading user
 * sees onboarding once too, same as a fresh install. Never reset by
 * this app itself once `true` — "redo onboarding" was explicitly
 * scoped out (see the onboarding-flow plan's NOT-in-scope section).
 */
onboarding_completed?: boolean }
export type DailyActivityDto = { date: string; count: number }
export type HistoryEntryDto = { timestamp: number; duration_secs: number; text: string; language: string; engine: string }
export type LanguageStatDto = { language: string; count: number; average_wpm: number }
/**
 * Wire-format twin of `history::LatencyPercentiles`.
 */
export type LatencyPercentilesDto = { p50_ms: number | null; p95_ms: number | null; samples: number }
/**
 * Wire-format twin of `history::LatencyStats` — backs the Stats page's
 * Latency table (frontend-rewrite plan, 2026-08-31).
 */
export type LatencyStatsDto = { recording: LatencyPercentilesDto; inference: LatencyPercentilesDto }
export type MetricsDto = { sessions: number; words: number; time_saved_minutes: number; average_wpm: number; total_dictation_minutes: number }
/**
 * Which permission a Grant button targets — one enum instead of a
 * stringly-typed `kind: String` (matches `SettingField`'s own established
 * pattern, D3 from the frontend-rewrite plan). Shared by the onboarding
 * window's Permissions step and the dashboard's Settings panel.
 */
export type PermissionKind = "microphone" | "accessibility" | "screen_recording"
export type PermissionStatusDto = { mic: string; accessibility: string; system_audio: string }
/**
 * Selects which boolean field `set_bool_setting` (`lib.rs`) writes — one
 * small enum instead of seven near-identical dedicated commands (DRY),
 * while tauri-specta still generates a fully-typed TS union for it, so the
 * frontend can never pass a typo'd/stringly-typed field name (the reason a
 * fully generic `set_setting(key: String, ...)` was rejected during
 * `/plan-eng-review` — see the frontend-rewrite plan's D3).
 */
export type SettingField = "pasteAutomatically" | "restoreClipboard" | "capitaliseSentences" | "tidyPunctuation" | "removeFillerWords" | "spokenFormatting" | "applySpokenCorrections"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
